"""add language to posts

Revision ID: 24371b96b744
Revises: 03387485ab19
Create Date: 2019-09-22 13:27:14.925492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24371b96b744'
down_revision = '03387485ab19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
